apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-pvc-{{ .Release.Namespace }}
  labels:
    app: movie-{{ .Release.Namespace }}
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
