apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres_cast-pvc-{{ .Release.Namespace }}
  labels:
    app: cast-{{ .Release.Namespace }}
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
